### ISSUE TITLE
对于同时填写了cookie和密码的站点，在cookie登录失败后尝试用密码登录。

### ISSUE THREAD

**Issue by vivodi** [IvonWei/flexget_qbittorrent_mod#101]
`hdpost`、`jpopsuki` 等站点同时支持 cookie 和密码登录。目前，在同时填写了 cookie 和密码的情况下，只会使用 cookie 登录。期望的行为是在cookie登录失败后尝试用密码登录再试一次。

**Comment by madwind** [comment]
考虑过 但意义不大 大部分能用cookie的都是长期有效的 如果需要使用登录 那就不要配置cookie 否则只是增加无意义的尝试，除非把登陆后的cookie保存下来用于下次访问
