### ISSUE TITLE
wiki中的分号是中文的

### ISSUE THREAD

**Issue by vivodi** [IvonWei/flexget_qbittorrent_mod#103]
[wiki](https://github.com/madwind/flexget_qbittorrent_mod/wiki#:~:text=PUID%3A%201000-,PGID%EF%BC%9A1000,-FG_LOG_LEVEL%3A%20INFO) 中`PGID：1000`的分号是中文的（应该用英文分号）。如果使用者直接从wiki复制粘贴会导致错误。

**Comment by madwind** [comment]
已处理

**Comment by vivodi** [comment]
能不能处理一下 madwind/docker-flexget#3
