### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by loveyoufoever** [IvonWei/flexget_qbittorrent_mod#104]
车pt签到报错response.state_code=403
空报错IAM Certification fails
麻烦看看这两个站点是不是不能签到？
另外是不是也不支持套？

**Comment by madwind** [comment]
1. cf盾
2. baidu ocr认证问题
3. ttg不允许

**Comment by loveyoufoever** [comment]
cf盾有什么办法绕过么？

**Comment by madwind** [comment]
没有
