### ISSUE TITLE
自动签到馒头503出现持续一周左右

### ISSUE THREAD

**Issue by zzzqu** [IvonWei/flexget_qbittorrent_mod#107]
1: m-team 2022-07-06 Reason: Sign_in=> response.status_code=503

**Comment by madwind** [comment]
开cf盾了 换cookie登录

**Comment by zzzqu** [comment]
[/tasks/sign_in/auto_sign_in/sites/m-team] Got `cf_clearance=xxxxxxxI9ZU2mW4JnTpDyIeRmaKU-1655917756-0-150; tp=MWIyZDliNWFiZGZiMjg2ZWU5N2RkxxxxxxM2YQ%3D%3D`, expected: dict
cookie登陆配置文件报错

**Comment by madwind** [comment]
m-team:
          cookie: 'xxxxxxxx'
          secret_key: <secret_key>

**Comment by HaifeiGeng** [comment]
你好大佬, 我已经按照这个配置, 使用cookie登录, 目前无法实现签到功能, 希望得到你的帮助,
我的配置:
m-team:
          cookie: '_ga=xxxxxxxxxxxxxxxxxxx; cf_clearance=xxxxxxxxxxxxxx; tp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

异常结果:
m-team 2022-09-23 Reason: Sign_in=> Detected CloudFlare DDoS-GUARD

希望得到您的回复, 感谢 @madwind

**Comment by madwind** [comment]
> 你好大佬, 我已经按照这个配置, 使用cookie登录, 目前无法实现签到功能, 希望得到你的帮助, 我的配置: m-team: cookie: '_ga=xxxxxxxxxxxxxxxxxxx; cf_clearance=xxxxxxxxxxxxxx; tp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
> 
> 异常结果: m-team 2022-09-23 Reason: Sign_in=> Detected CloudFlare DDoS-GUARD
> 
> 希望得到您的回复, 感谢 @madwind

获取的cookie需要 ip user_agent 与 flexget 一致，正常登录后，重新获取cookie试试
