### ISSUE TITLE
CloudFlare DDoS-GUARD问题

### ISSUE THREAD

**Issue by richard-guan-dev** [IvonWei/flexget_qbittorrent_mod#109]
请问Log返回这个CloudFlare DDoS-GUARD， 这个是有办法解决的吗？

**Comment by madwind** [comment]
暂时没有

**Comment by badpinkman** [comment]
你好大佬, @madwind 
请问现在馒头一直都报这个错, 是大家都这样 还是我设置的不对呢?
FAILED: `m-team 2022-09-23` by auto_sign_in plugin because sign_in=> Detected CloudFlare DDoS-GUARD
感谢.

**Comment by madwind** [comment]
> 你好大佬, @madwind 请问现在馒头一直都报这个错, 是大家都这样 还是我设置的不对呢? FAILED: `m-team 2022-09-23` by auto_sign_in plugin because sign_in=> Detected CloudFlare DDoS-GUARD 感谢.

我已经回答过你了 如果做了还是不行 那我就没办法

**Comment by badpinkman** [comment]
我刚才的Issue让我给删了, 我没有注意自己的邮箱, 导致问题重新又问了一次, 我已经看到您的回答, 感谢您. 一会我去试试.
