### ISSUE TITLE
dmhy签到失败

### ISSUE THREAD

**Issue by Pollo3470** [IvonWei/flexget_qbittorrent_mod#113]
Failed dmhy 2022-07-27 (Sign_in=> Network error: url: https://u2.dmhy.org/showup.php?action=show, error: HTTPSConnectionPool(host='u2.dmhy.org', port=443): Max retries exceeded with url: /showup.php?action=show (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))

请问这是什么原因导致的？
还有就是u2的username是填用户名还是邮箱？现在登录用的是邮箱

**Comment by madwind** [comment]
1 .网络
2. 用户名，签到记录显示的用户名
