### ISSUE TITLE
最新版不支持m-team的二次验证登录了

### ISSUE THREAD

**Issue by xujipm** [IvonWei/flexget_qbittorrent_mod#117]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/3202911/183578925-1b4020be-1ace-4fc3-baca-44ce02b36c4f.png">

**Comment by madwind** [comment]
https://github.com/madwind/flexget_qbittorrent_mod/blob/master/config_example.yml#L158

**Comment by xujipm** [comment]
谢谢大佬，刚看wiki的说明还是支持账号密码的
https://github.com/madwind/flexget_qbittorrent_mod/wiki/auto_sign_in

**Comment by madwind** [comment]
支持账号 secret_key 换了位置而已
