### ISSUE TITLE
hdsky签到错误

### ISSUE THREAD

**Issue by 13229896070** [IvonWei/flexget_qbittorrent_mod#122]
v0.8.12和最新版，只要添加hdsky签到，就会报错Did not pass schema 
log

```
 CRITICAL manager                       [/tasks/sign_in/auto_sign_in/sites/hdsky] Got `c_secure_uid=xx; c_secure_pass=xx; c_secure_ssl=xx; c_secure_login=xx`, expected: dict
2022-09-13 01:29:51 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
```

config.yml :
```
      sites:
        hdsky: 'c_secure_uid; c_secure_pass=; c_secure_ssl=; c_secure_tracker_ssl=; c_secure_login'
```

**Comment by madwind** [comment]
https://github.com/madwind/flexget_qbittorrent_mod/blob/master/config_example.yml#L139

**Comment by 13229896070** [comment]
> https://github.com/madwind/flexget_qbittorrent_mod/blob/master/config_example.yml#L139

配置了十多个站点，只要不填写hdsky就不会报错，签到都能成功。只要添加hdsky就会报语法错误，删除就没问题了

**Comment by 13229896070** [comment]
> https://github.com/madwind/flexget_qbittorrent_mod/blob/master/config_example.yml#L139

Thank u
