### ISSUE TITLE
TG消息推送报错 no chat id found

### ISSUE THREAD

**Issue by z4jst** [IvonWei/flexget_qbittorrent_mod#123]
大佬你好。
LOG中显示：no chat id found, try manually sending the bot any message to initialize the chat
也给机器人发过消息，但是依然报错。

配置如下：
          - telegram_mod:
              bot_token: '5****:*****' #这个是用的 bot father 回传的 bot token
             #发送统计图片
              image: 'details_report.png'
              recipients:
                - username: '113****111' #这个用的 userinfobot 上回传的 接收人账号ID，也试过 直接用TG上 用户名，也一样报错

**Comment by madwind** [comment]
username 是 @xxxxx 不包括@

**Comment by z4jst** [comment]
谢谢！要保证大小写完全正确。
