### ISSUE TITLE
 无法访问数据

### ISSUE THREAD

**Issue by Duan-rax** [IvonWei/flexget_qbittorrent_mod#124]
1: beyond-hd 2022-10-01  Reason: Sign_in=> Url: https://beyond-hd.me redirect to https://beyond-hd.me/
2: dmhy 2022-10-01  Reason: Sign_in=> No permission to access data
3: hdcity 2022-10-01  Reason: Sign_in=> Sign in failed, no sign in
5: hdsky 2022-10-01  Reason: Sign_in=> No permission to access data
8: open 2022-10-01  Reason: Sign_in=> No permission to access data

**Comment by madwind** [comment]
检查baidu ocr
