### ISSUE TITLE
lemonhd提示Reason: Details=> detail: join_date not found.

### ISSUE THREAD

**Issue by xujipm** [IvonWei/flexget_qbittorrent_mod#125]
1: lemonhd 2022-10-08 Reason: Details=> detail: join_date not found.
但是配置文件不支持配置 lemonhd 的 join_date
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/3202911/194702456-a46d1148-473d-415b-b667-21cb0640f255.png">

**Comment by madwind** [comment]
更新插件
