### ISSUE TITLE
安装提示错误

### ISSUE THREAD

**Issue by zhimadelvdou** [IvonWei/flexget_qbittorrent_mod#130]
具体错误:Error response from daemon: invalid mode: /downloads.
安装命令行
docker run -d \
    --name=flexget \
    --restart always \
    -p 3539:3539 \
    -v G:\downloads:/downloads \
    -v D:\Docker\flexget\config:/config \
    -e PUID=1000 \
    -e PGID=1000 \
    -e TZ=Asia/Shanghai \
    -e FG_WEBUI_PASSWD=MEDBq4faQK6$%WYr \
    madwind/flexget

**Comment by zhimadelvdou** [comment]
使用的是docker desktop for win最新版本

**Comment by zhimadelvdou** [comment]
是不是容器内/downloads路径应该为 /config/downloads     ?

**Comment by zhimadelvdou** [comment]
已通过图形界面安装成功.
问题出在哪里还是没想明白

**Comment by ProteinPig** [comment]
restart=always
少了等号

**Comment by madwind** [comment]
没用过win 试试G:/downloads

**Comment by zhimadelvdou** [comment]
我安装好后一直没时间研究脚本,所以也就丢在那边了.后来我在安装其他镜像时也遇到这个问题,后来我找到的问题还是路径格式的问题.最终我尝试下来应该是这样.去掉盘符的冒号然后前面也要加/以表示绝对路径/例:-v /D/Docker/config:/config
