### ISSUE TITLE
PTTime签到失败

### ISSUE THREAD

**Issue by badpinkman** [IvonWei/flexget_qbittorrent_mod#134]
如题, 麻烦大佬有空帮忙看下, 今天尝试重新登录, 使用新的cookie, 然而并没有作用.
日志: 
REJECTED: `pttime 2023-01-04` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Sign_in=> Sign in failed, no sign in)

感谢.

**Comment by madwind** [comment]
贴完整log

**Comment by badpinkman** [comment]
今天运行的时候, 发现签到成功了, 上方的日志是在测试的时候出现的. 抱歉.
