### ISSUE TITLE
gainbound有错误信息

### ISSUE THREAD

**Issue by matthkewk** [IvonWei/flexget_qbittorrent_mod#135]
The following sites have failed for task sign_in:
1: gainbound 2023-01-08 这是您的第 7 次签到，已连续签到 7 天，本次签到获得 45 个魔力值。 Reason: Details=> detail: points not found.

大佬有空也请适配一下sharkpt.net

**Comment by madwind** [comment]
gainbound 已更新，没有sharkpt 无法适配
