### ISSUE TITLE
flexget 3.1.135 疑似和mod不兼容了

### ISSUE THREAD

**Issue by barton0426** [IvonWei/flexget_qbittorrent_mod#14]
之前的docker镜像都正常build使用，今天更新了一波之后 config报错 auto_sign_in不是支持的插件
上一个能正常使用的flexget版本是 3.1.134

**Comment by madwind** [comment]
135移除了 chardet ，你可以自己装一个上去

**Comment by barton0426** [comment]
> 135移除了 chardet ，你可以自己装一个上去

已解决，非常感谢！
