### ISSUE TITLE
请问是否可以改用chat id而不是username作为telegram的通知对象

### ISSUE THREAD

**Issue by christaikobo** [IvonWei/flexget_qbittorrent_mod#151]
用username还要获取chat id，经常遇到没对话要手动输入个字符，不如直接输入chat id方便...

**Comment by madwind** [comment]
现在的tg插件是继承于官方tg的改版，它只支持 python-telegram-bot==12.8 ，我没记错的话 应该是不可以的，具体什么原因我也忘记了

**Comment by christaikobo** [comment]
OK 谢谢回复！
