### ISSUE TITLE
AvistaZ签到失败

### ISSUE THREAD

**Issue by christaikobo** [IvonWei/flexget_qbittorrent_mod#152]
日志如下
```
ERROR       entry                                       Failed avistaz 2024-03-04 (Sign_in=> Sign in failed, no sign in. (None))
WARNING     flexget.plugins.ptsites.base.sign_in        no sign in, regex: ['<title>AvistaZ Beta 3.0</title>'], content: <!doctype html>
```

使用的是 `avistaz: 'cookie'`的格式

**Comment by madwind** [comment]
把content:  <!doctype html>后面的贴多几行看看

**Comment by christaikobo** [comment]
@madwind 因日志太长且包含个人信息，所以邮件发送了，请查收一下，谢谢！

**Comment by christaikobo** [comment]
另，我发现avistaz似乎只能保留一个活动session，也就是说每次网页登录之后都要在签到程序里更新cookie...

**Comment by madwind** [comment]
已修复
> 另，我发现avistaz似乎只能保留一个活动session，也就是说每次网页登录之后都要在签到程序里更新cookie...

这就没什么好办法了 除非改成模拟登录

**Comment by christaikobo** [comment]
感谢修复！
测试了一下，的确是不再报错了。应该是原来匹配的标题的`beta 3.0`那行字没了吧...

> 这就没什么好办法了 除非改成模拟登录

我猜也是，这个还是有别的办法的。

总而言之非常感谢！
