### ISSUE TITLE
Iyuu 自动辅种提示需要升级接口

### ISSUE THREAD

**Issue by yuaner66** [IvonWei/flexget_qbittorrent_mod#155]
> `http://api.bolahg.cn/index.php?s=App.Api.Infohash Error: {'ret': 400, 'data': {}, 'msg': '非法请求：请及时升级至新版接口 http://doc.iyuu.cn/reference/reseed_index', 'version': '2.0.0'}`

这个提示有段时间了，能否更新一下

**Comment by madwind** [comment]
已修复
