### ISSUE TITLE
Want to add a site

### ISSUE THREAD

**Issue by badpinkman** [IvonWei/flexget_qbittorrent_mod#160]
大佬, 有空能否增加个站点:
bitporn.eu

**Comment by madwind** [comment]
已添加

**Comment by badpinkman** [comment]
大佬给力

**Comment by badpinkman** [comment]
大佬, 目前遇到了两个问题, 一个是今天新加的这个bitporn签到失败了, 日志:
`  File "/opt/python/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f532d47b970>, {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, lik...
               │                 │       └ 'input'
               │                 └ <PluginInfo(name=auto_sign_in)>
               └ <flexget.task.Task object at 0x7f532d47b970>

> File "/opt/python/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f532d47b970>, {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, lik...
             └ <Event(name=plugin.auto_sign_in.input,func=on_task_input,priority=128)>

  File "/opt/python/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f532d47b970>, {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, lik...
           │    └ <bound method PluginAutoSignIn.on_task_input of <flexget.plugins.auto_sign_in.PluginAutoSignIn object at 0x7f532f24ecd0>>
           └ <Event(name=plugin.auto_sign_in.input,func=on_task_input,priority=128)>

  File "/tmp/plugins/auto_sign_in.py", line 70, in on_task_input
    executor.build_sign_in_entry(entry, config)
    │        │                   │      └ {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36', 'max_...
    │        │                   └ <Entry(title=bitporn 2024-08-15,state=undecided)>
    │        └ <function build_sign_in_entry at 0x7f533fbbd280>
    └ <module 'flexget.plugins.ptsites.executor' from '/tmp/plugins/ptsites/executor.py'>

  File "/tmp/plugins/ptsites/executor.py", line 38, in build_sign_in_entry
    site_class = get_site_class(entry['class_name'])
                 │              └ <Entry(title=bitporn 2024-08-15,state=undecided)>
                 └ <function get_site_class at 0x7f533fbbd790>

  File "/tmp/plugins/ptsites/executor.py", line 130, in get_site_class
    site_module = importlib.import_module(f'flexget.plugins.ptsites.sites.{class_name.lower()}')
                  │         └ <function import_module at 0x7f534b86a550>
                  └ <module 'importlib' from '/var/fc/lang/python3.9/lib/python3.9/importlib/__init__.py'>

  File "/var/fc/lang/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.ptsites.sites.bitporn'
           │          └ <function _gcd_import at 0x7f534b9a0310>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'flexget.plugins.ptsites.sites.bitporn'
2024-08-15 13:20:30 CRITICAL manager       sign_in         An unexpected crash has occurred. Writing crash report to /tmp/crash_report.2024.08.15.132030938576.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.3.19
2024-08-15 13:20:30 WARNING  task          sign_in         Aborting task (plugin: auto_sign_in)`

第二个问题, femdomcult这个站今天发现也失败了:
日志:
Url: https://femdomcult.org/index.php redirect to https://femdomcult.org/. (None)

希望大佬有时间帮忙看下 感谢!
