### ISSUE TITLE
更新telegram_mod, 支持使用chat_id

### ISSUE THREAD

**Issue by christaikobo** [IvonWei/flexget_qbittorrent_mod#168]
flexget官方支持的`python-telegram-bot`已经不再局限于12.8, 目前已支持使用`chat_id`作为recepient, 详见: https://github.com/Flexget/Flexget/pull/4083

请问telegram_mod是否有可能更新以支持该功能呢

感谢!

**Comment by madwind** [comment]
我觉得这个pr有些问题,发送消息用了异步 感觉违背了flexget什么都同步执行的一贯设计, 这样在分段发送消息的时候有可能导致消息顺序错乱, 等下个版本发布如果官方还没改或者没人提issue 我再跟着改

**Comment by christaikobo** [comment]
@vivodi 正好大佬也是本项目的contributor, @一下请教大佬意见

**Comment by madwind** [comment]
看来是我理解错了, 这个pr已经集成了mod的功能 直接使用现在官方的telegram就可以了 不需要使用mod了, 稍后我会把telegram_mod删掉

**Comment by christaikobo** [comment]
感谢解答, 提醒一下wiki里面的示例config.yml最好也改一下
