### ISSUE TITLE
作者删除功能可以设置分类吗?

### ISSUE THREAD

**Issue by 2375399351** [IvonWei/flexget_qbittorrent_mod#29]
qbittorrent_delete_keeper_template:
这个里面好像没有分类功能
如果不用check_reseed:这个进行检查的话，会导致所有的旧种子都被删除吗？
后的自动删种带分类，但是不带删除文件的功能，qbittorrent_delete_keeper_template
我希望可以自动删除指定分类里面的种子及文件，这个功能有没有办法实现？求教

**Comment by madwind** [comment]
wiki下有完整配置和注释

**Comment by 2375399351** [comment]
> wiki下有完整配置和注释

`  #删除
  qbittorrent_delete_keeper_template:
    qbittorrent_mod:
      action:
        remove:
          cleaner:
            #删种同时数据
            delete_files: true
  #自动删种
  delete:
    priority: 3
    #官方插件：disable 关闭任务记录 失败重试
    disable: [ seen, seen_info_hash, retry_failed, history ]
    #官方插件： if 过滤器
    if:
      #参考entry属性列表
      #种子在 Rss分类 并且 最后活动时间 < 2天 
      - qbittorrent_category in ['flexget'] and qbittorrent_last_activity < now - timedelta(days=2): accept
      #当种子不属于 reseed 时，检测做种时间，防止hr
      - "'reseed' not in qbittorrent_tags":
          if:
            #当 tags 带有 pt1 时，检测做种时间，小于48小时则拒绝
            -  "'pt1' in qbittorrent_tags and qbittorrent_seeding_time<48*60*60": reject
    #官方sort_by插件：按最后活动时间从早到晚排序 优先删除
    sort_by: qbittorrent_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template`

这么设置的话是不是就只会自动删除flexget这个分类下的种子及文件了?我主要怕qbittorrent_delete_keeper_template这个功能会单独运行删除种子，因为这个功能下面没有目录分类的功能

**Comment by 2375399351** [comment]
#删除
  qbittorrent_delete_keeper_template:
    qbittorrent_mod:
      action:
        remove:
          cleaner:
            #删种同时数据
            delete_files: true
  #自动删种
  delete:
    priority: 3
    #官方插件：disable 关闭任务记录 失败重试
    disable: [ seen, seen_info_hash, retry_failed, history ]
    #官方插件： if 过滤器
    if:
      #参考entry属性列表
      #种子在 Rss分类 并且 最后活动时间 < 2天 
      - qbittorrent_category in ['flexget'] and qbittorrent_last_activity < now - timedelta(days=2): accept
      #当种子不属于 reseed 时，检测做种时间，防止hr
      - "'reseed' not in qbittorrent_tags":
          if:
            #当 tags 带有 pt1 时，检测做种时间，小于48小时则拒绝
            -  "'pt1' in qbittorrent_tags and qbittorrent_seeding_time<48*60*60": reject
    #官方sort_by插件：按最后活动时间从早到晚排序 优先删除
    sort_by: qbittorrent_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template

**Comment by madwind** [comment]
1.是

2.qbittorrent_delete_keeper_template 是模板，能删什么东西 是filter 决定的，qbittorrent_delete_keeper_template 是 output，你大概理解 input -> filter -> output 这条线就行

**Comment by 2375399351** [comment]
> 1.是
> 
> 2.qbittorrent_delete_keeper_template 是模板，能删什么东西 是filter 决定的，qbittorrent_delete_keeper_template 是 output，你大概理解 input -> filter -> output 这条线就行

好的，谢谢
