### ISSUE TITLE
U2签到经常失败

### ISSUE THREAD

**Issue by Hurray0** [IvonWei/flexget_qbittorrent_mod#31]
看了一下日志是ORC的锅 现在是规定次数没有识别出来就直接报错不再获取数据也不签到了
能否配置一个变量设置获取不到数据就随便选一个签到；或者没能签到也识别数据？

**Comment by madwind** [comment]
ocr_config:
        retry: 20
        char_count: 1
        score: 1
char_count  score 改成 1，和随便签到就没什么区别了

没能签到也识别数据：不能  不符合flexget的重试逻辑
