### ISSUE TITLE
1ptba和52pt签到失败

### ISSUE THREAD

**Issue by barton0426** [IvonWei/flexget_qbittorrent_mod#33]
这两个站一直签到失败 更新agent 同步ip后配置的cookie也不行

**Comment by madwind** [comment]
log

**Comment by barton0426** [comment]
Sorry.
Failed 52pt 2022-02-03 (Sign_in=> Url: https://52pt.site/bakatest.php redirect to https://52pt.site/login.php?returnto=bakatest.php)
Failed 1ptba 2022-02-03 (Sign_in=> Url: https://1ptba.com/attendance.php redirect to https://1ptba.com/login.php?returnto=attendance.php)

**Comment by madwind** [comment]
直接复制cookie 不要右键copy value，保证cookie的值都是url encode状态

**Comment by barton0426** [comment]
尝试后重启docker 仍然无效 log与之前相同
其它40多个站都正常签到无误

**Comment by madwind** [comment]
如果你无法解决 那你只能给我cookie看看有什么问题了 这两个站没见有人说过有问题

**Comment by barton0426** [comment]
已发gmail邮箱 麻烦了！

**Comment by madwind** [comment]
我用你的cookie签到并没有问题 给我发这个站的签到配置

**Comment by madwind** [comment]
你的意思是 上面那两个换了行 缩进也不对的站点cookie 是你的配置？

**Comment by barton0426** [comment]
cookie我复制进去是没有换行的 保存后flexget自动换了行 邮件里1ptba的缩进少一个空格是我远程桌面操作少选了

**Comment by madwind** [comment]
我还没遇过flexget自动换行的 你把整个 yml 文件发给我看看 就要和签到有关的配置
