### ISSUE TITLE
作者每个任务添加种子可以设置单独分类吗？

### ISSUE THREAD

**Issue by 2375399351** [IvonWei/flexget_qbittorrent_mod#43]
目前好像只能设置总的分类，能不能做到任务1，下载分类是1，任务2，下载分类是2？

**Comment by madwind** [comment]
1.不用template
2.覆盖
https://flexget.com/Plugins/template

**Comment by 2375399351** [comment]
好像可以

**Comment by 2375399351** [comment]
> 1.不用template
> 
> 2.覆盖
> 
> https://flexget.com/Plugins/template

我直接把qbittorrent_mod写在了task下，不知道会不会生效
原来qbittorrent_add_template下的qbittorrent_mod我没有删除
正常应该是先从task里面获取qbottorrent_mod的设置，没有的话再从qbittorrent_add_template中获取qbittorrent_mod的设置
应该是这么理解的吧？
