### ISSUE TITLE
作者，有没有可能做个flexget ck过期通知

### ISSUE THREAD

**Issue by 2375399351** [IvonWei/flexget_qbittorrent_mod#56]
有时候ck过期了还不知道，不知道有没有可能有这个功能?

**Comment by madwind** [comment]
用cookie签到 失败基本就是过期了

**Comment by 2375399351** [comment]
> 用cookie签到 失败基本就是过期了 

懂了，但是有办法获取log中ck过期的信息再发送到tg吗？

**Comment by madwind** [comment]
签到结果都保存在 entry['result'] 写notify模板提取

**Comment by 2375399351** [comment]
> 签到结果都保存在 entry['result'] 写notify模板提取

好的，我还是签到来检测吧，谢谢回复

**Comment by vivodi** [comment]
@2375399351 是什么站cookie过期？有没有可能可以做成用密码而不是cookie登录的方式？

**Comment by 2375399351** [comment]
> @2375399351 是什么站cookie过期？有没有可能可以做成用密码而不是cookie登录的方式？

ourbits，可以账号密码登陆，但是我不知道作者这个下载种子能不能用账号密码登陆，我指的不是签到，是下free种
