### ISSUE TITLE
是否能够增加 丐帮 站点的支持？

### ISSUE THREAD

**Issue by ruicky** [IvonWei/flexget_qbittorrent_mod#74]
站点地址：https://gainbound.net/
本来想提 MR ，但是没有相应的对接文档，其中的字段值，不知道该如何写。

**Comment by madwind** [comment]
我没有这个站，或者晚点我写点文档

**Comment by ruicky** [comment]
好的 期待文档

**Comment by madwind** [comment]
暂且先这样吧，有不懂的再说https://github.com/madwind/flexget_qbittorrent_mod/wiki/auto_sign_in#%E9%80%82%E9%85%8D
