### ISSUE TITLE
对不需要签到的站点，直接访问个人详情页从而避免非必要的网页爬取

### ISSUE THREAD

**Issue by vivodi** [IvonWei/flexget_qbittorrent_mod#75]
## 目前的问题
目前，对无签到任务的站点在生成用户数据时会先访问主页，然后在主页中通过正则匹配找到个人详情页的UID，然后再访问个人详情页。事实上，可以直接访问个人详情页，在生成用户数据时直接使用 `base_content` 即可，从而省去了访问主页与正则匹配。

### 方法1
由使用者将UID填写到 `config.yml` 中。
优点：程序实现较简单。
缺点：使用不便；有兼容性问题，用户的config.yml需要重新编写。
### 方法2（推荐）
程序首次运行后将UID回写至 `config.yml` 或 `db-config.sqlite` 中。
优点：使用方便。
缺点：尚不清楚回写至 `config.yml` 或 `db-config.sqlite` 怎么实现。

**Comment by vivodi** [comment]
注：以上内容只是我对本项目签到功能如何改进的一些脑洞，不一定是必须的或是很有用的。如果觉得没有必要，可以直接关闭issue。如果觉得有必要，我可以酌情PR。

**Comment by madwind** [comment]
回写`config.ym`l还是会因为引用其它`yaml`问题变得复杂，写`db-config.sqlite`大概比较好处理吧，但是有人提出过不想获取统计，所以真的要做，我宁愿选第一种，配置可选 str 或 dict,类似 cookie 或者 login

**Comment by madwind** [comment]
我想了一下
`auto_sign_in.py` 可以增加一个保存 cookie 的 yaml 文件配置 例如: `cookie_yaml: cookie.yaml`
以及`yaml`内`cookie`的路径 例如 `sites_path: variables.sites`
最好能考虑把iyuu需要的passkey也一并获取了

**Comment by madwind** [comment]
尝试之后，发现实现起来挺复杂的，使用 `yaml` 模块，锚点是个大麻烦，回写yml会导致锚点消失，flexget引用文件又无法使用template或者锚点。也可能是我没研究透彻
总之现在除非自己处理格式，替换原有配置，否则似乎没有更好的解决办法
所以如果没有更好的想法 还是关了吧 感觉实现起来挺麻烦的

测试 `get_user_id()` 后保存 uid
回写至 secret.yml, 无法触发flexget自动重载配置, 无法在 `config.yml` 中使用锚点
```py
def saveUid(entry, uid):
    path = 'variables.sites'
    with open('secret.yml', 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f) or {}
        for s in path.split('.'):
            x = data.get(s)
        if not x:
            x = {}
        if entry['uid'] != uid:
            with open('secret.yml', 'w', encoding='utf-8') as f:
                if isinstance(entry['site_config'], str):
                    x[entry["site_name"]] = {'cookie': entry['cookie'], 'uid': uid}
                else:
                    x[entry["site_name"]]['cookie'] = entry['cookie']
                    x[entry["site_name"]]['uid'] = uid
                data['variables'] = data.get('variables') or {}
                data['variables']['sites'] = x
                yaml.dump(data, f, Dumper=yaml.Dumper, width=4096)

```

**Comment by vivodi** [comment]
我没看懂你写的。你的做法是在一个新的配置文件 `secret.yml` 中保存uid，对吗？ 
1.  `saveUid` 要在哪里调用？
2. 什么是 _无法触发flexget自动重载配置,_ 
3. 什么是 _无法在 `config.yml` 中使用锚点_ ？既然存储在了 `secret.yml` 中，那还和 `config.yml` 有什么关系？
4. 什么是 _flexget引用文件又无法使用template或者锚点_

**Comment by madwind** [comment]
不单是保存uid 也要保存cookie，login之类的配置，准确的说应该是修改当前配置增加 uid
get_user_id() 后调用就行，这不是什么问题，关键在于yml的写入
修改了config.yml flexget可以自动 reload, 但 variables 引用其它yml的不行
variables : secret.yml 只能以变量的形式使用，不能使用锚点或者模板
