### ISSUE TITLE
将新的cookie或新的bearer token回写至config.yml

### ISSUE THREAD

**Issue by vivodi** [IvonWei/flexget_qbittorrent_mod#76]
## 目前的问题
有的网站在cookie即将到期的时候，会种下新的cookie或新的bearer token从而避免登录到期。但是本程序运行时无法保存种下的新cookie或bearer token。而有时适配密码登录是不可行的，阻碍包括但不限于复杂的验证码（如reCAPTCHA）和cf盾（项目中的那个过盾组件好像目前过不了盾）。

## 可能的实现方法
如果发现网站种下新的cookie或bearer token，将其回写至config.yml中。

**Comment by vivodi** [comment]
注：并不清楚是否有这样的PT站具有上述行为。以上内容只是我对本项目签到功能如何改进的一些脑洞，不一定是必须的或是很有用的。如果觉得没有必要，可以直接关闭issue。如果觉得有必要，我可以酌情PR。

**Comment by madwind** [comment]
我也考虑过为登录的站点保存cookie 但是回写config是比较麻烦的 你不知道到底配置在了哪里 因为还有类似引用别的配置文件这种操作 我能想到的也只有写入数据库了 但是也还有cookie变量引用  所以得把所有涉及cookie的插件都做适配才行 `iyuu_auto_reseed` `html_rss` `auto_sign_in`
cf盾去年就失效了 暂时没找到什么纯py的好办法
