### ISSUE TITLE
自动签到报错

### ISSUE THREAD

**Issue by loveyoufoever** [IvonWei/flexget_qbittorrent_mod#91]
自动签到报错是什么原因？
'Entry' object has no attribute 'fail_with_prefix'ix'

**Comment by madwind** [comment]
重新pull

**Comment by loveyoufoever** [comment]
> 重新pull

好了。谢谢大佬！
另外，有没办法自己添加自定义站点？就比如说观众和丐帮

**Comment by madwind** [comment]
已经有了
