### ISSUE TITLE
html_rss的配置怎么配置？

### ISSUE THREAD

**Issue by loveyoufoever** [IvonWei/flexget_qbittorrent_mod#98]
跟着模板找css选择器的教程跟着学着试了试，馒头的貌似匹配到数据了，但是观众的貌似一直获取不到。麻烦老大帮忙看看观众的组件选择器对不对？
root_element_selector: '#outer > table > tbody > tr.sticky_top'

**Comment by madwind** [comment]
没看到有 #outer
F12 在 console 里 document.querySelector('table > tbody > tr.sticky_top') 试试就知道了

**Comment by loveyoufoever** [comment]
测试了可以了。但是方法还是不是很理解，有没哪里有详细的教程可以获取到组件选择器的值？

**Comment by madwind** [comment]
没有了 都是写 css选择器 而已，https://www.w3school.com.cn/cssref/css_selectors.asp

**Comment by loveyoufoever** [comment]
这种是通过抓取静态页面的方式取得免费信息的么？

**Comment by madwind** [comment]
种子列表
